Repository PaladinCloud/CE, pull requests merged in 2023-03, with the labels that each got.

#883 bug:sorting dates in fix-central
  webapp/src/app/shared/pipes/order-by.pipe.ts
Labels: external contribution

#882 bug-fix:violation-search-bar-cursor
  webapp/src/app/shared/table/table.component.css
  webapp/src/app/shared/table/table.component.html
Labels: external contribution

#945 Fix: rename-column-to-violationID
  webapp/src/app/pacman-features/modules/compliance/issue-listing/issue-listing.component.spec.ts
  webapp/src/app/pacman-features/modules/compliance/issue-listing/issue-listing.component.ts
Labels: external contribution

#974 Issue#969 Changed column name from Title to Policy
  webapp/src/app/pacman-features/modules/compliance/policy-knowledgebase/policy-knowledgebase.component.ts
Labels: external contribution

#942 Rename Creation On to Date Created on policy details page
  webapp/src/app/pacman-features/modules/compliance/policy-knowledgebase-details/policy-knowledgebase-details.component.html
Labels: external contribution

#947 getting started images replaced
  webapp/src/assets/images/know-your-dashboard/know-your-dashboard-1.png
  webapp/src/assets/images/know-your-dashboard/know-your-dashboard-2.png
  webapp/src/assets/images/know-your-dashboard/know-your-dashboard-3.png
  webapp/src/assets/images/know-your-dashboard/know-your-dashboard-4.png
  webapp/src/assets/images/know-your-dashboard/know-your-dashboard-5.png
Labels: external contribution

#978 fix:wrap label in treemap
  webapp/src/app/pacman-features/modules/assets/asset-distribution/asset-distribution.component.ts
Labels: external contribution

#1003 fix: violations by severity tile legend order
  webapp/src/app/pacman-features/secondary-components/issues-trend-history/issues-trend-history.component.ts
  webapp/src/app/pacman-features/services/issues-history.service.ts
Labels: external contribution

#1001 fix: updated violations by severity title
  webapp/src/app/pacman-features/secondary-components/issues-trend-history/issues-trend-history.component.css
  webapp/src/app/pacman-features/secondary-components/issues-trend-history/issues-trend-history.component.html
Labels: external contribution

#1023 Bug: dashboard custom date empty menu
  webapp/src/app/pacman-features/modules/compliance/card/card.component.ts
  webapp/src/app/shared/components/molecules/custom-card/custom-card.component.ts
  webapp/src/app/shared/date-selection/date-selection.component.css
  webapp/src/app/shared/date-selection/date-selection.component.html
  webapp/src/app/shared/dropdown/dropdown.component.ts
Labels: bug, external contribution

#1019 feat: center text compliance dashboard & compliance trend legend order
  webapp/src/app/pacman-features/modules/compliance/violations-card/violations-card.component.css
  webapp/src/app/pacman-features/modules/compliance/violations-card/violations-card.component.html
  webapp/src/app/pacman-features/modules/compliance/violations-card/violations-card.component.ts
  webapp/src/app/pacman-features/secondary-components/compliance-overview-trend/compliance-overview-trend.component.ts
  webapp/src/app/pacman-features/services/compliance-overview.service.ts
Labels: external contribution

#1030 feat: policy knowledgebase filtration
  webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.ts
  webapp/src/app/pacman-features/modules/compliance/policy-knowledgebase/policy-knowledgebase.component.css
  webapp/src/app/pacman-features/modules/compliance/policy-knowledgebase/policy-knowledgebase.component.html
  webapp/src/app/pacman-features/modules/compliance/policy-knowledgebase/policy-knowledgebase.component.ts
  webapp/src/app/shared/table/table.component.html
Labels: enhancement, external contribution

#1028 Adding autofixAvailable flag to the noncompliance api endpoint, code …
  api/pacman-api-asset/pom.xml
  api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/controller/ComplianceController.java
  api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/repository/ComplianceRepositoryImpl.java
  api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/ComplianceService.java
  api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/ComplianceServiceImpl.java
  api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/IssueTrendServiceImpl.java
  api/pacman-api-compliance/src/main/java/com/tmobile/pacman/api/compliance/service/PatchingServiceImpl.java
  api/pacman-api-compliance/src/main/resources/bootstrap.yml
  api/pacman-api-compliance/src/test/java/com/tmobile/pacman/api/compliance/controller/ComplianceControllerTest.java
  api/pacman-api-compliance/src/test/java/com/tmobile/pacman/api/compliance/service/ComplianceServiceImplTest.java
  api/pacman-api-compliance/src/test/java/com/tmobile/pacman/api/compliance/service/IssueTrendServiceImplTest.java
  commons/pac-api-commons/src/main/java/com/tmobile/pacman/api/commons/Constants.java
Labels: enhancement

#1024 Feat/policy kb details screen
  webapp/src/app/pacman-features/modules/compliance/policy-knowledgebase-details/policy-knowledgebase-details.component.css
  webapp/src/app/pacman-features/modules/compliance/policy-knowledgebase-details/policy-knowledgebase-details.component.html
  webapp/src/app/pacman-features/modules/compliance/policy-knowledgebase-details/policy-knowledgebase-details.component.ts
  webapp/src/app/shared/models/policy-data.model.ts
Labels: external contribution
