Repository PaladinCloud/CE, pull requests merged in 2023-04, with the labels that each got.

#1041 feat(table-component): clearing serach input and filters, when clear button clicked
  webapp/src/app/shared/table/table.component.html
  webapp/src/app/shared/table/table.component.ts
Labels: enhancement, external contribution

#1050 feat(issue-listing): row size has been set to small
  webapp/src/app/pacman-features/modules/compliance/issue-listing/issue-listing.component.html
  webapp/src/app/pacman-features/modules/compliance/issue-listing/issue-listing.component.ts
Labels: enhancement, external contribution

#1058 feat: asset-list row style
  webapp/src/app/pacman-features/modules/assets/asset-list/asset-list.component.html
  webapp/src/app/pacman-features/modules/assets/asset-list/asset-list.component.ts
  webapp/src/app/post-login-app/common/contextual-menu/contextual-menu.component.ts
Labels: enhancement, external contribution

#894 Fix: policy-violation-desc.html
  webapp/src/app/pacman-features/secondary-components/policy-violation-desc/policy-violation-desc.component.html
Labels: external contribution

#1073 Feat/notifications enhancements1
  webapp/package.json
  webapp/src/app/pacman-features/modules/notifications/cloud-notifications/cloud-notifications.component.html
  webapp/src/app/pacman-features/modules/notifications/cloud-notifications/cloud-notifications.component.ts
  webapp/src/app/pacman-features/modules/notifications/notification-details/notification-details.component.html
  webapp/src/app/pacman-features/modules/notifications/notification-details/notification-details.component.ts
  webapp/src/app/pacman-features/modules/notifications/notifications.module.ts
Labels: enhancement

#1101 feat: asset summary page
  webapp/src/app/pacman-features/modules/assets/asset-dashboard/asset-dashboard.component.css
  webapp/src/app/pacman-features/modules/assets/asset-dashboard/asset-dashboard.component.html
  webapp/src/app/pacman-features/modules/assets/asset-dashboard/asset-dashboard.component.ts
  webapp/src/app/shared/components/molecules/overview-tile/overview-tile.component.css
  webapp/src/app/shared/components/molecules/overview-tile/overview-tile.component.html
  webapp/src/app/shared/components/molecules/overview-tile/overview-tile.component.ts
  webapp/src/assets/icons/exempted-assets-icon.svg
  webapp/src/assets/icons/total-assets-icon.svg
Labels: enhancement, external contribution

#1162 feat(numbers-formatting): asset count
  webapp/src/app/post-login-app/default-asset-group/default-asset-group.component.html
Labels: enhancement, external contribution

#1157 feat(cloud-notifications): applied date pipe to created date
  webapp/src/app/pacman-features/modules/notifications/cloud-notifications/cloud-notifications.component.ts
Labels: enhancement, external contribution

#1172 feat: dashboard container collapse
  webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.css
  webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.html
  webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.ts
  webapp/src/app/pacman-features/modules/compliance/services/dashboard-arrangement.service.ts
Labels: enhancement, external contribution

#1175 feat(compliance-dashboard): navigation to violations by category
  webapp/src/app/pacman-features/modules/compliance/card/card.component.css
  webapp/src/app/pacman-features/modules/compliance/card/card.component.html
  webapp/src/app/pacman-features/modules/compliance/card/card.component.ts
  webapp/src/app/pacman-features/modules/compliance/compliance-dashboard/compliance-dashboard.component.html
  webapp/src/app/pacman-features/modules/compliance/progress-bar-chart/progress-bar-chart.component.css
  webapp/src/app/pacman-features/modules/compliance/progress-bar-chart/progress-bar-chart.component.html
  webapp/src/app/pacman-features/modules/compliance/progress-bar-chart/progress-bar-chart.component.ts
Labels: enhancement, external contribution
